[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/access"
  to = "/.netlify/functions/access"
  status = 200

[[redirects]]
  from = "/manifest.webmanifest"
  to = "/.netlify/functions/manifest"
  status = 200
  force = true
